import {StyleSheet} from 'react-native';
import theme from '../../config/theme';

const styles = StyleSheet.create({
  TextInput: {
    borderStyle: 'dashed',
  },

  root: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 'auto',
    width: '100%',
    padding: '5%',
  },
  metaProfile: {
    flex: 1,
    marginTop: '5%',
    alignItems: 'center',
  },
  profileImage: {
    flex: 1,
    width: 150,
    maxHeight: 150,
    alignSelf: 'center',
    borderRadius: 75,
  },
  name: {
    fontSize: theme.font.subHeader,
    letterSpacing: 0.3,
    lineHeight: 25,
    marginVertical: '5%',
    minWidth: '50%',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: theme.fonts.heavy,
    color: theme.palette.darkGrey,
  },
  status: {
    fontSize: theme.font.subtitle,
    color: theme.palette.blue,
    fontWeight: 'bold',
    paddingVertical: '5%',
  },
  editableStatus: {
    fontSize: theme.font.subtitle,
    color: theme.palette.blue,
    fontWeight: 'bold',
    marginVertical: '1%',
    height: 20,
    width: 100,
  },
  locationStatus: {
    fontSize: theme.font.paragraph,
    color: theme.palette.darkGrey,
    fontFamily: theme.fonts.regular,
    // marginVertical: '1%',
    minWidth: '20%',
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  locationMetrix: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: '1%',
  },

  interest: {
    flex: 1,
    marginVertical: '3%',
    height: 'auto',
  },
  section: {
    flex: 1,
    marginVertical: '5%',
    height: 'auto',
    minWidth: '100%',
  },
  sectionTitle: {
    flex: 1,
    textAlign: 'center',
    fontWeight: 'bold',
    color: theme.palette.darkGrey,
    fontSize: theme.font.subtitle,
    fontFamily: theme.fonts.regular,
    marginBottom: '2%',
  },
  bio: {
    alignSelf: 'center',
    justifyContent: 'center',
    maxWidth: '80%',
    marginTop: '3%',
    textAlign: 'justify',
    fontFamily: theme.fonts.regular,
    fontSize: theme.font.subtitle,
    color: theme.palette.darkGrey,
  },
  sectionContent: {
    flex: 1,
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignContent: 'center',
    marginTop: '3%',
    textAlign: 'justify',
  },
  icon: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationIcon: {
    height: 15,
    width: 15,
    marginRight: '2%',
  },
  favesTitle: {
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    color: theme.palette.darkGrey,
    fontWeight: '900',
    marginTop: 5,
  },
  toMeetImage: {
    height: 50,
    width: 50,
    marginVertical: '5%',
  },
  globe: {
    textAlignVertical: 'center',
    textAlign: 'center',
    marginVertical: '3%',
    marginHorizontal: 1,
    fontSize: theme.font.subtitle,
    fontFamily: theme.fonts.bold,
    backgroundColor: theme.palette.blue,
    color: '#FFFFFF',
    fontWeight: 'bold',
    paddingHorizontal: '5%',
    paddingVertical: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  unselectedGlobe: {
    textAlignVertical: 'center',
    textAlign: 'center',
    marginVertical: '3%',
    marginHorizontal: 1,
    fontSize: theme.font.subtitle,
    fontFamily: theme.fonts.bold,
    backgroundColor: '#FFFFFF',
    borderColor: theme.palette.blue,
    borderWidth: 1,
    color: theme.palette.blue,
    fontWeight: 'bold',
    paddingHorizontal: '5%',
    paddingVertical: 10,
    borderRadius: 15,
  },
  removeIcon: {
    color: theme.palette.red,
    fontSize: 25,
  },
  saveButton: {
    flex: 1,
    marginVertical: '1%',
    height: 'auto',
  },
  logout: {
    color: theme.palette.red,
    fontWeight: 'bold',
    fontFamily: theme.fonts.regular,
    marginRight: 10,
  },
  buttonWrapper: {
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
  },
  menuSelector: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '50%',
    borderColor: theme.palette.lightGrey,
    borderWidth: 1,
    marginBottom: '2%',
  },
  selectedSelector: {
    color: theme.palette.blue,
    paddingHorizontal: '3%',
    paddingVertical: '1%',
    minWidth: '50%',
    textAlign: 'center',
  },
  textInput: {
    borderColor: theme.palette.lightGrey,
    borderWidth: 0.5,
    borderStyle: 'solid',
    padding: '4%',
  },
  modal: {
    flex: 1,
    backgroundColor: 'white',
    paddingTop: '20%',
    alignContent: 'center',
  },
  modalButtons: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    marginTop: '5%',
  },
  modalConfirm: {
    backgroundColor: theme.palette.blue,
    color: 'white',
    borderColor: 'white',
    borderRadius: 5,
    borderWidth: 2,
    paddingHorizontal: '4%',
    fontSize: theme.font.subHeader,
    paddingVertical: '10%',
    marginHorizontal: '2%',
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: theme.fonts.bold,
  },
  modalCancel: {
    backgroundColor: 'white',
    color: theme.palette.blue,
    borderColor: theme.palette.blue,
    fontSize: theme.font.subHeader,
    borderRadius: 5,
    borderWidth: 2,
    paddingHorizontal: '4%',
    paddingVertical: '10%',
    marginHorizontal: '2%',
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: theme.fonts.bold,
  },

  attentionImage: {
    flex: 1,
    width: 150,
    maxHeight: 150,
    alignSelf: 'center',
  },
});

export default styles;
