const theme = {
  palette: {
    green: '#0DB14B',
    blue: '#00A3B4',
    lightBlue: '#CFE3E6',
    lightGrey: '#CFCFCF',
    mediumGrey: '#979797',
    darkGrey: '#4D4D4F',
    red: '#D86060',
    darkBlue: '#34495e',
  },
  font: {
    header: 25,
    subHeader: 20,
    subtitle: 15,
    paragraph: 10,
  },
  fonts: {
    black: 'Lato-Black',
    blackItalic: 'Lato-BlackItalic',
    bold: 'Lato-Bold',
    boldItalic: 'Lato-BoldItalic',
    hairline: 'Lato-Hairline',
    hairlineItalic: 'Lato-HairlineItalic',
    heavy: 'Lato-Heavy',
    heavyItalic: 'Lato-HeavyItalic',
    italic: 'Lato-Italic',
    light: 'Lato-Light',
    lightItalic: 'Lato-LightItalic',
    medium: 'Lato-Medium',
    mediumItalic: 'Lato-MediumItalic',
    regular: 'Lato-Regular',
    regularItalic: 'Lato-RegularItalic',
    semibold: 'Lato-Semibold',
    semiboldItalic: 'Lato-SemiboldItalic',
    thin: 'Lato-Thin',
    thinItalic: 'Lato-ThinItalic',
  },
};

export default theme;
